# Generated by Django 3.1.5 on 2021-03-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.JSONField(default=None, verbose_name='Содержание'),
            preserve_default=False,
        ),
    ]
