# Generated by Django 3.1.5 on 2021-03-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='short_description',
            field=models.TextField(default='', max_length=256, verbose_name='Краткое описание'),
            preserve_default=False,
        ),
    ]
