# Generated by Django 3.1.5 on 2021-03-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_message_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='category',
            field=models.CharField(choices=[('Спорт', 'Спорт'), ('Политика', 'Политика'), ('Наука', 'Наука'), ('Мир', 'Мир'), ('Культура', 'Культура'), ('Экономика', 'Экономика'), ('Интернет', 'Интернет')], default='none', max_length=64, verbose_name='Категория'),
        ),
    ]
