# Generated by Django 3.1.5 on 2021-03-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210303_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.JSONField(null=True, verbose_name='Содержание'),
        ),
    ]
