# Generated by Django 3.1.5 on 2021-03-03 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.JSONField(default=None, verbose_name='Содержание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='message',
            name='img',
            field=models.ImageField(blank=True, upload_to='messages', verbose_name='Картинка'),
        ),
    ]
