# Generated by Django 3.1.5 on 2021-03-03 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210303_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
    ]
