# Generated by Django 3.1.5 on 2021-03-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_message_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='category',
            field=models.CharField(choices=[('Небольшой', 'Небольшой'), ('Средний', 'Средний'), ('Большой', 'Большой')], default='none', max_length=64, verbose_name='Категория'),
        ),
    ]
