# Generated by Django 3.1.5 on 2021-03-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20210303_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.JSONField(blank=True, null=True, verbose_name='Содержание'),
        ),
    ]
