# Generated by Django 3.1.5 on 2021-04-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20210303_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='view_counter',
            field=models.IntegerField(default=0, null=True, verbose_name='Счетчик просмотров'),
        ),
    ]
